name: CI

on:
  push:
    branches:
      - master
      - beta
      - sdk-release/**
      - feature/**
  pull_request:
    branches:
      - master
      - beta
      - sdk-release/**
      - feature/**

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest &&
          $HOME/go/bin/staticcheck &&
          make vet

  test:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         go:
           - "1.19"
           - "1.18"
           - "1.17"
           - "1.16"
           - "1.15"
     name: "Test: go v${{ matrix.go }}"
     steps:
       - uses: actions/checkout@v2
       - name: Setup go
         uses: actions/setup-go@v1
         with:
           go-version: ${{ matrix.go }}
       - name: Start stripe-mock
         run: docker run -d -p 12111-12112:12111-12112 stripe/stripe-mock && sleep 5
       - name: Test
         run: make test &&
              make bench &&
              make check-api-clients
       - name: Coveralls
         run: make coverage && make coveralls
         if: matrix.go == '1.16'
         env:
           COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           COVERALLS_FLAG_NAME: Go-${{ matrix.go }}
